import javax.swing.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

public class ThirdForm extends javax.swing.JFrame {

    /**
     * Creates new form ThirdForm
     */
    public int AyatNo = 0;
    protected String word;
    public Tree[] bst;
    
    public ThirdForm() {
        initComponents();
    }
    
    public ThirdForm(String word, int AyatNo, Tree[] bst) {
        this.word = word;
        this.AyatNo = bst[word.charAt(0)-97].find(word).getAyats().get(AyatNo);
        this.bst = bst;
        initComponents();
        loadTranslations();
    }


    //O(N)
    public void loadTranslations(){
        int an = AyatNo%1000;
        int sn = AyatNo/1000;
        String[] t = new String[2];
        BufferedReader reader;
	try {
            String file = Main.FilePath + "\\src\\Translations.txt";
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_16));
            String line = reader.readLine();
            while(line != null){
                int c = line.indexOf(" ");
                int n1 = Integer.parseInt(line.substring(0,c));
                int n2 = Integer.parseInt(line.substring(c+1));
                for(int i = 1 ; i <= n2; i++){
                    line = reader.readLine();
                    if(n1 == sn){
                        c = line.indexOf("  ");
                        int verse = Integer.parseInt(line.substring(0,c));
                        line = line.substring(c+1);
                        if(verse == an){
                            c = line.indexOf("  ");
                            t[0] = line.substring(0,c);
                            t[1] = line.substring(c+1);
                            break;
                        }
                    }
                }
                line = reader.readLine();
            }
            reader.close();
	} catch (Exception e) {
            System.out.println("exception in Translations");
	}
        arabic.setText(t[0]);
        english.setText(t[1]);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */




    @SuppressWarnings("unchecked")
    // <editor-fold default state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel mainPanel = new JPanel();
        JLabel name = new JLabel();
        JLabel text = new JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton backButton = new JButton();
        JButton searchButton = new JButton();
        JPanel jPanel1 = new JPanel();
        arabic = new javax.swing.JLabel();
        english = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QURAN EXPLORER");

        mainPanel.setBackground(new java.awt.Color(100, 200, 200));
        mainPanel.setMaximumSize(new java.awt.Dimension(400, 320));

        name.setFont(new java.awt.Font("Tahoma", Font.BOLD, 48)); // NOI18N
        name.setForeground(new java.awt.Color(255, 204, 0));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("قرآن");

        text.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("AYAT ("+AyatNo/1000 + ":" + AyatNo%1000 +") TRANSLATION"
        );

        backButton.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(this::BackButtonActionPerformed);

        searchButton.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        searchButton.setText("Search Again");
        searchButton.addActionListener(this::SearchButtonActionPerformed);

        jPanel1.setBackground(new java.awt.Color(100, 200, 200));

        arabic.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        arabic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        english.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        english.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arabic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(english, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arabic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(english)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                        .addComponent(searchButton)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(searchButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        SecondForm form = new SecondForm(word, bst);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        this.setVisible(false);this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        FirstForm form = new FirstForm();
            form.setLocationRelativeTo(this);
            form.setVisible(true); 
            this.setVisible(false);this.dispose();
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ThirdForm().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arabic;
    private javax.swing.JLabel english;
    // End of variables declaration//GEN-END:variables
}

